[pytest]
testpaths = tests
norecursedirs = multi_lang plugins distributed temp .* scripts
python_files = test_*.py
python_classes = Test*
filterwarnings =
    ignore::pytest.PytestCollectionWarning


