stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements-dev.txt
    - python -m unittest discover -s tests -t .

package_artifacts:
  stage: build
  image: python:3.10
  script:
    - python setup.py bdist_wheel
  artifacts:
    paths:
      - dist/
