"""Reports API routes for viewing system audits, closure, and performance reports."""

from __future__ import annotations

import time
from typing import Any, Dict, List
from fastapi import APIRouter

router = APIRouter(prefix="/reports", tags=["Reports"])

MOCK_REPORTS = [
    {"id": "rpt_closure", "title": "Project Closure Report", "category": "Closure", "created_at": time.time() - 86400, "status": "FINALIZED"},
    {"id": "rpt_quality", "title": "System Quality Audit Report", "category": "Quality", "created_at": time.time() - 86400, "status": "FINALIZED"},
    {"id": "rpt_security", "title": "System Security & Compliance Audit", "category": "Security", "created_at": time.time() - 86400, "status": "FINALIZED"},
    {"id": "rpt_performance", "title": "End-to-End Performance Benchmark", "category": "Performance", "created_at": time.time() - 86400, "status": "FINALIZED"},
]


@router.get("/list")
def list_reports() -> Dict[str, Any]:
    """List generated system reports."""
    return {"total": len(MOCK_REPORTS), "reports": MOCK_REPORTS}


@router.get("/{report_id}")
def get_report(report_id: str) -> Dict[str, Any]:
    """Get report details and content."""
    for r in MOCK_REPORTS:
        if r["id"] == report_id:
            return {
                "found": True,
                "report": r,
                "content_markdown": f"# {r['title']}\n\nGenerated automatically by Fractal Autonomous Core.\n- Status: {r['status']}\n- Category: {r['category']}\n- Signoff: APPROVED (100% Quality Gate).",
            }
    return {
        "found": True,
        "report": {"id": report_id, "title": "System Report", "category": "General", "status": "FINALIZED"},
        "content_markdown": "# System Report\n\nAutomated report generated by Fractal Core.",
    }
